export const ENDPOINTS = {
  register: 'users/register',
  login: 'users/login',
  logout: 'users/logout',
  catalog: 'data/episodes?distinct=name&sortBy=name',
  addEpisode: 'data/episodes',
	likeEpisode: 'data/likes',
  details: (episodeId: string) => `data/episodes/${episodeId}`,
  edit: (episodeId: string) => `data/episodes/${episodeId}`,
  delete: (episodeId: string) => `data/episodes/${episodeId}`,
  canLike: (episodeId: string, userId: string) => `data/likes?where=episodeId%3D%22${episodeId}%22%20and%20_ownerId%3D%22${userId}%22&count`,
	episodeTotalLikes: (episodeId: string) => `data/likes?where=episodeId%3D%22${episodeId}%22&distinct=_ownerId&count`,
  search: (query: string) => `data/episodes?where=name%20LIKE%20%22${query}%22`,
	personalEpisodes: (userId: string) => `data/episodes?where=_ownerId%3D%22${userId}%22&sortBy=name`,
};
